WITH MAXY AS
    (SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE,
     YEAR(DIFFERENTIATION_DATE) AS YEAR 
     FROM ECOLI_DATA GROUP BY YEAR)


SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    M.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID 
    FROM ECOLI_DATA AS A , MAXY AS M 
    WHERE YEAR(DIFFERENTIATION_DATE) = M.YEAR 
    ORDER BY YEAR, YEAR_DEV;
    